services: 
  api_model:
    build: .
    image: pqa_api:latest
    container_name: pqa_container
    ports: 
      - "8000:8000"
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=Production
      - APP_ENV=production
    
