services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.9.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: "YOUR_SECRET_KEY"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      CSV_PATH: ${CSV_PATH}
      PROJECT_DB: ${PROJECT_DB}

    volumes:
      - ./dags:/opt/airflow/dags 
      - ./logs:/opt/airflow/logs 
      - ../src:/opt/airflow/src 
      - ../data:/opt/airflow/data 
      - ../models:/opt/airflow/models
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: HNVOFQWbPTFqsfr_enxCXCJC4LCS3Q7ECsWbGAjrF5k=
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      CSV_PATH: /opt/airflow/data/raw_data.csv
      PROJECT_DB: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

    volumes: 
      - ./dags:/opt/airflow/dags 
      - ./logs:/opt/airflow/logs 
      - ../src:/opt/airflow/src 
      - ../data:/opt/airflow/data 
      - ../models:/opt/airflow/models
    command: scheduler

  airflow-init:
    image: apache/airflow:2.9.1
    entrypoint: ""
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags 
      - ./logs:/opt/airflow/logs 
      - ../src:/opt/airflow/src 
      - ../data:/opt/airflow/data 
      - ../models:/opt/airflow/models
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "

volumes:
  postgres_db:
